# DB Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/smartcontact?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Tupu@4321

spring.jpa.hibernate.ddl-auto=update


# Cloudinary Configuration
cloudinary.cloud_name=dqr8hqui5
cloudinary.api_key=261489114378282
cloudinary.api_secret=9cVHfr8SF3d-yorCGXmOdv4fgqI