spring.application.name=smartcontactmanager

server.port=${PORT:9191}

#DB Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

app.base-url=${BASE_URL:http://localhost:9191}

# Email Setting
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS}
app.mail.from=${APP_MAIL_FROM}


#Session Timeout
server.servlet.session.timeout=15m

#Image Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
server.tomcat.max-swallow-size=-1

# ================= GOOGLE LOGIN =================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email


# ================= GOOGLE CONTACTS =================
spring.security.oauth2.client.registration.google-contacts.client-id=${GOOGLE_CONTACTS_CLIENT_ID}
spring.security.oauth2.client.registration.google-contacts.client-secret=${GOOGLE_CONTACTS_CLIENT_SECRET}

spring.security.oauth2.client.registration.google-contacts.scope=openid,profile,email,https://www.googleapis.com/auth/contacts.readonly

spring.security.oauth2.client.registration.google-contacts.redirect-uri={baseUrl}/login/oauth2/code/google-contacts

spring.security.oauth2.client.registration.google-contacts.provider=google

# GITHUB OAuth2 Configuration
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.security.oauth2.client.provider.github.user-name-attribute=login

# Cloudinary Configuration
cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${CLOUDINARY_SECRET}

# RazorPay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}

spring.devtools.restart.enabled=true
server.forward-headers-strategy=framework

# logging.level.org.springframework.security=DEBUG




